# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .provider_client import ProviderClient
from .version import VERSION

__all__ = ['ProviderClient']

__version__ = VERSION

