// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConnectionRecord
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionRecord class.
        /// </summary>
        public ConnectionRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionRecord class.
        /// </summary>
        /// <param name="state">Possible values include: 'Invited',
        /// 'Negotiating', 'Connected'</param>
        public ConnectionRecord(ConnectionAlias alias = default(ConnectionAlias), AgentEndpoint endpoint = default(AgentEndpoint), string state = default(string), string id = default(string))
        {
            Alias = alias;
            Endpoint = endpoint;
            State = state;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alias")]
        public ConnectionAlias Alias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpoint")]
        public AgentEndpoint Endpoint { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Invited', 'Negotiating',
        /// 'Connected'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
