// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConnectionAlias
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionAlias class.
        /// </summary>
        public ConnectionAlias()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionAlias class.
        /// </summary>
        public ConnectionAlias(string name = default(string), string imageUrl = default(string))
        {
            Name = name;
            ImageUrl = imageUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

    }
}
