// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateInvitation
    {
        /// <summary>
        /// Initializes a new instance of the CreateInvitation class.
        /// </summary>
        public CreateInvitation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateInvitation class.
        /// </summary>
        public CreateInvitation(string email = default(string), string name = default(string))
        {
            Email = email;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
