// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Create verification
    /// </summary>
    public partial class CreateVerification
    {
        /// <summary>
        /// Initializes a new instance of the CreateVerification class.
        /// </summary>
        public CreateVerification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateVerification class.
        /// </summary>
        /// <param name="proofRequestId">Gets or sets the proof request
        /// identifier.</param>
        /// <param name="connectionId">Gets or sets the connection
        /// identifier.</param>
        public CreateVerification(string proofRequestId = default(string), string connectionId = default(string))
        {
            ProofRequestId = proofRequestId;
            ConnectionId = connectionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the proof request identifier.
        /// </summary>
        [JsonProperty(PropertyName = "proofRequestId")]
        public string ProofRequestId { get; set; }

        /// <summary>
        /// Gets or sets the connection identifier.
        /// </summary>
        [JsonProperty(PropertyName = "connectionId")]
        public string ConnectionId { get; set; }

    }
}
