// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents a request object to create new credential definition for an
    /// agency
    /// </summary>
    public partial class CreateDefinition
    {
        /// <summary>
        /// Initializes a new instance of the CreateDefinition class.
        /// </summary>
        public CreateDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateDefinition class.
        /// </summary>
        /// <param name="schemaId">Schema identifier for this
        /// definition</param>
        /// <param name="name">Name of the schema.</param>
        /// <param name="version">Schema version.</param>
        /// <param name="attrNames">Schema attribute names.</param>
        /// <param name="supportRevocation">Support credential
        /// revocation</param>
        /// <param name="maxCount">Maximum credential count.</param>
        public CreateDefinition(string schemaId = default(string), string name = default(string), string version = default(string), IList<string> attrNames = default(IList<string>), bool? supportRevocation = default(bool?), int? maxCount = default(int?))
        {
            SchemaId = schemaId;
            Name = name;
            Version = version;
            AttrNames = attrNames;
            SupportRevocation = supportRevocation;
            MaxCount = maxCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets schema identifier for this definition
        /// </summary>
        [JsonProperty(PropertyName = "schema_id")]
        public string SchemaId { get; set; }

        /// <summary>
        /// Gets or sets name of the schema.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets schema version.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets schema attribute names.
        /// </summary>
        [JsonProperty(PropertyName = "attr_names")]
        public IList<string> AttrNames { get; set; }

        /// <summary>
        /// Gets or sets support credential revocation
        /// </summary>
        [JsonProperty(PropertyName = "support_revocation")]
        public bool? SupportRevocation { get; set; }

        /// <summary>
        /// Gets or sets maximum credential count.
        /// </summary>
        [JsonProperty(PropertyName = "max_count")]
        public int? MaxCount { get; set; }

    }
}
