// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateInvitation
    {
        /// <summary>
        /// Initializes a new instance of the CreateInvitation class.
        /// </summary>
        public CreateInvitation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateInvitation class.
        /// </summary>
        /// <param name="email">Gets or sets the tenant identifier.</param>
        /// <param name="name">Gets or sets the connection identifier.</param>
        /// <param name="multiParty">Gets or sets a value indicating whether
        /// [multi party].</param>
        public CreateInvitation(string email = default(string), string name = default(string), bool? multiParty = default(bool?))
        {
            Email = email;
            Name = name;
            MultiParty = multiParty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the tenant identifier.
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the connection identifier.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [multi party].
        /// </summary>
        [JsonProperty(PropertyName = "multiParty")]
        public bool? MultiParty { get; set; }

    }
}
