// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DefinitionRecord
    {
        /// <summary>
        /// Initializes a new instance of the DefinitionRecord class.
        /// </summary>
        public DefinitionRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DefinitionRecord class.
        /// </summary>
        public DefinitionRecord(bool? supportsRevocation = default(bool?), bool? requireApproval = default(bool?), string id = default(string))
        {
            SupportsRevocation = supportsRevocation;
            RequireApproval = requireApproval;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supportsRevocation")]
        public bool? SupportsRevocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requireApproval")]
        public bool? RequireApproval { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
