// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Provisioning info.
    /// </summary>
    public partial class ProvisioningInfo
    {
        /// <summary>
        /// Initializes a new instance of the ProvisioningInfo class.
        /// </summary>
        public ProvisioningInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProvisioningInfo class.
        /// </summary>
        /// <param name="issuerDid">Gets or sets the issuer did.</param>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="imageUrl">Gets or sets the image URL.</param>
        /// <param name="endpoint">Gets or sets the endpoint.</param>
        public ProvisioningInfo(string issuerDid = default(string), string name = default(string), string imageUrl = default(string), AgentEndpoint endpoint = default(AgentEndpoint))
        {
            IssuerDid = issuerDid;
            Name = name;
            ImageUrl = imageUrl;
            Endpoint = endpoint;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the issuer did.
        /// </summary>
        [JsonProperty(PropertyName = "issuerDid")]
        public string IssuerDid { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the image URL.
        /// </summary>
        [JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or sets the endpoint.
        /// </summary>
        [JsonProperty(PropertyName = "endpoint")]
        public AgentEndpoint Endpoint { get; set; }

    }
}
