// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RevocationInterval
    {
        /// <summary>
        /// Initializes a new instance of the RevocationInterval class.
        /// </summary>
        public RevocationInterval()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RevocationInterval class.
        /// </summary>
        public RevocationInterval(int? fromProperty = default(int?), int? to = default(int?))
        {
            FromProperty = fromProperty;
            To = to;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public int? FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public int? To { get; set; }

    }
}
