// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Portal.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Verification Info
    /// </summary>
    public partial class VerificationInfo
    {
        /// <summary>
        /// Initializes a new instance of the VerificationInfo class.
        /// </summary>
        public VerificationInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VerificationInfo class.
        /// </summary>
        /// <param name="connectionId">Gets or sets the connection
        /// identifier.</param>
        /// <param name="verificationId">Gets or sets the verification
        /// identifier.</param>
        /// <param name="state">Gets or sets the state. Possible values
        /// include: 'Requested', 'Accepted', 'Rejected'</param>
        public VerificationInfo(string connectionId = default(string), string verificationId = default(string), string state = default(string))
        {
            ConnectionId = connectionId;
            VerificationId = verificationId;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the connection identifier.
        /// </summary>
        [JsonProperty(PropertyName = "connectionId")]
        public string ConnectionId { get; set; }

        /// <summary>
        /// Gets or sets the verification identifier.
        /// </summary>
        [JsonProperty(PropertyName = "verificationId")]
        public string VerificationId { get; set; }

        /// <summary>
        /// Gets or sets the state. Possible values include: 'Requested',
        /// 'Accepted', 'Rejected'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

    }
}
