# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .agent_endpoint_py3 import AgentEndpoint
    from .connection_contract_py3 import ConnectionContract
    from .credential_contract_py3 import CredentialContract
    from .proof_attribute_contract_py3 import ProofAttributeContract
    from .verification_policy_restriction_attribute_py3 import VerificationPolicyRestrictionAttribute
    from .verification_policy_restriction_py3 import VerificationPolicyRestriction
    from .verification_policy_attribute_contract_py3 import VerificationPolicyAttributeContract
    from .verification_policy_predicate_contract_py3 import VerificationPolicyPredicateContract
    from .verification_policy_revocation_reqirement_py3 import VerificationPolicyRevocationReqirement
    from .verification_policy_parameters_py3 import VerificationPolicyParameters
    from .proposed_attribute_py3 import ProposedAttribute
    from .proposed_predicate_py3 import ProposedPredicate
    from .proof_proposal_py3 import ProofProposal
    from .verification_contract_py3 import VerificationContract
    from .verification_policy_credential_parameters_py3 import VerificationPolicyCredentialParameters
    from .verification_policy_credential_contract_py3 import VerificationPolicyCredentialContract
    from .custodian_wallet_contract_py3 import CustodianWalletContract
    from .wallet_parameters_py3 import WalletParameters
except (SyntaxError, ImportError):
    from .agent_endpoint import AgentEndpoint
    from .connection_contract import ConnectionContract
    from .credential_contract import CredentialContract
    from .proof_attribute_contract import ProofAttributeContract
    from .verification_policy_restriction_attribute import VerificationPolicyRestrictionAttribute
    from .verification_policy_restriction import VerificationPolicyRestriction
    from .verification_policy_attribute_contract import VerificationPolicyAttributeContract
    from .verification_policy_predicate_contract import VerificationPolicyPredicateContract
    from .verification_policy_revocation_reqirement import VerificationPolicyRevocationReqirement
    from .verification_policy_parameters import VerificationPolicyParameters
    from .proposed_attribute import ProposedAttribute
    from .proposed_predicate import ProposedPredicate
    from .proof_proposal import ProofProposal
    from .verification_contract import VerificationContract
    from .verification_policy_credential_parameters import VerificationPolicyCredentialParameters
    from .verification_policy_credential_contract import VerificationPolicyCredentialContract
    from .custodian_wallet_contract import CustodianWalletContract
    from .wallet_parameters import WalletParameters

__all__ = [
    'AgentEndpoint',
    'ConnectionContract',
    'CredentialContract',
    'ProofAttributeContract',
    'VerificationPolicyRestrictionAttribute',
    'VerificationPolicyRestriction',
    'VerificationPolicyAttributeContract',
    'VerificationPolicyPredicateContract',
    'VerificationPolicyRevocationReqirement',
    'VerificationPolicyParameters',
    'ProposedAttribute',
    'ProposedPredicate',
    'ProofProposal',
    'VerificationContract',
    'VerificationPolicyCredentialParameters',
    'VerificationPolicyCredentialContract',
    'CustodianWalletContract',
    'WalletParameters',
]
