# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProofProposal(Model):
    """ProofProposal.

    :param comment:
    :type comment: str
    :param proposed_attributes:
    :type proposed_attributes: list[~wallet.models.ProposedAttribute]
    :param proposed_predicates:
    :type proposed_predicates: list[~wallet.models.ProposedPredicate]
    """

    _attribute_map = {
        'comment': {'key': 'comment', 'type': 'str'},
        'proposed_attributes': {'key': 'proposedAttributes', 'type': '[ProposedAttribute]'},
        'proposed_predicates': {'key': 'proposedPredicates', 'type': '[ProposedPredicate]'},
    }

    def __init__(self, *, comment: str=None, proposed_attributes=None, proposed_predicates=None, **kwargs) -> None:
        super(ProofProposal, self).__init__(**kwargs)
        self.comment = comment
        self.proposed_attributes = proposed_attributes
        self.proposed_predicates = proposed_predicates
