# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProposedAttribute(Model):
    """ProposedAttribute.

    :param name:
    :type name: str
    :param credential_definition_id:
    :type credential_definition_id: str
    :param schema_id:
    :type schema_id: str
    :param issuer_did:
    :type issuer_did: str
    :param mime_type:
    :type mime_type: str
    :param value:
    :type value: str
    :param referent:
    :type referent: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'credential_definition_id': {'key': 'credentialDefinitionId', 'type': 'str'},
        'schema_id': {'key': 'schemaId', 'type': 'str'},
        'issuer_did': {'key': 'issuerDid', 'type': 'str'},
        'mime_type': {'key': 'mimeType', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
        'referent': {'key': 'referent', 'type': 'str'},
    }

    def __init__(self, *, name: str=None, credential_definition_id: str=None, schema_id: str=None, issuer_did: str=None, mime_type: str=None, value: str=None, referent: str=None, **kwargs) -> None:
        super(ProposedAttribute, self).__init__(**kwargs)
        self.name = name
        self.credential_definition_id = credential_definition_id
        self.schema_id = schema_id
        self.issuer_did = issuer_did
        self.mime_type = mime_type
        self.value = value
        self.referent = referent
