# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VerificationPolicyCredentialContract(Model):
    """VerificationPolicyCredentialContract.

    :param policy_name:
    :type policy_name: str
    :param attribute_names:
    :type attribute_names: list[str]
    :param available_credentials:
    :type available_credentials: list[~wallet.models.CredentialContract]
    """

    _attribute_map = {
        'policy_name': {'key': 'policyName', 'type': 'str'},
        'attribute_names': {'key': 'attributeNames', 'type': '[str]'},
        'available_credentials': {'key': 'availableCredentials', 'type': '[CredentialContract]'},
    }

    def __init__(self, *, policy_name: str=None, attribute_names=None, available_credentials=None, **kwargs) -> None:
        super(VerificationPolicyCredentialContract, self).__init__(**kwargs)
        self.policy_name = policy_name
        self.attribute_names = attribute_names
        self.available_credentials = available_credentials
