# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VerificationPolicyParameters(Model):
    """VerificationPolicyParameters.

    All required parameters must be populated in order to send to Azure.

    :param name: Required.
    :type name: str
    :param version: Required.
    :type version: str
    :param attributes:
    :type attributes: list[~wallet.models.VerificationPolicyAttributeContract]
    :param predicates:
    :type predicates: list[~wallet.models.VerificationPolicyPredicateContract]
    :param revocation_requirement:
    :type revocation_requirement:
     ~wallet.models.VerificationPolicyRevocationReqirement
    """

    _validation = {
        'name': {'required': True},
        'version': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': '[VerificationPolicyAttributeContract]'},
        'predicates': {'key': 'predicates', 'type': '[VerificationPolicyPredicateContract]'},
        'revocation_requirement': {'key': 'revocationRequirement', 'type': 'VerificationPolicyRevocationReqirement'},
    }

    def __init__(self, *, name: str, version: str, attributes=None, predicates=None, revocation_requirement=None, **kwargs) -> None:
        super(VerificationPolicyParameters, self).__init__(**kwargs)
        self.name = name
        self.version = version
        self.attributes = attributes
        self.predicates = predicates
        self.revocation_requirement = revocation_requirement
