# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WalletParameters(Model):
    """Wallet parameters.

    :param wallet_id: The wallet identifier
     <remarks>
     This property can be null. If not set, a unique identifier will be
     generated
     </remarks>
    :type wallet_id: str
    :param owner_name: The owner name
    :type owner_name: str
    """

    _attribute_map = {
        'wallet_id': {'key': 'walletId', 'type': 'str'},
        'owner_name': {'key': 'ownerName', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(WalletParameters, self).__init__(**kwargs)
        self.wallet_id = kwargs.get('wallet_id', None)
        self.owner_name = kwargs.get('owner_name', None)
