# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .credentials_client import CredentialsClient
from .version import VERSION

__all__ = ['CredentialsClient']

__version__ = VERSION

