// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Cloud.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AgentEndpoint
    {
        /// <summary>
        /// Initializes a new instance of the AgentEndpoint class.
        /// </summary>
        public AgentEndpoint()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AgentEndpoint class.
        /// </summary>
        public AgentEndpoint(string did = default(string), string verkey = default(string), string uri = default(string))
        {
            Did = did;
            Verkey = verkey;
            Uri = uri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "did")]
        public string Did { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verkey")]
        public string Verkey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

    }
}
