// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Cloud.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConnectionInvitationMessage
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionInvitationMessage
        /// class.
        /// </summary>
        public ConnectionInvitationMessage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionInvitationMessage
        /// class.
        /// </summary>
        public ConnectionInvitationMessage(string label = default(string), string imageUrl = default(string), string serviceEndpoint = default(string), IList<string> routingKeys = default(IList<string>), IList<string> recipientKeys = default(IList<string>), string id = default(string), string type = default(string))
        {
            Label = label;
            ImageUrl = imageUrl;
            ServiceEndpoint = serviceEndpoint;
            RoutingKeys = routingKeys;
            RecipientKeys = recipientKeys;
            Id = id;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceEndpoint")]
        public string ServiceEndpoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "routingKeys")]
        public IList<string> RoutingKeys { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipientKeys")]
        public IList<string> RecipientKeys { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@type")]
        public string Type { get; set; }

    }
}
