// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Cloud.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CredentialInfo
    {
        /// <summary>
        /// Initializes a new instance of the CredentialInfo class.
        /// </summary>
        public CredentialInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CredentialInfo class.
        /// </summary>
        /// <param name="state">Possible values include: 'Offered',
        /// 'Requested', 'Issued', 'Rejected', 'Revoked'</param>
        public CredentialInfo(string credentialId = default(string), string state = default(string), string connectionId = default(string), string definitionId = default(string), string schemaId = default(string))
        {
            CredentialId = credentialId;
            State = state;
            ConnectionId = connectionId;
            DefinitionId = definitionId;
            SchemaId = schemaId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "credentialId")]
        public string CredentialId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Offered', 'Requested',
        /// 'Issued', 'Rejected', 'Revoked'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connectionId")]
        public string ConnectionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitionId")]
        public string DefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaId")]
        public string SchemaId { get; set; }

    }
}
