// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Cloud.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MessageInfo
    {
        /// <summary>
        /// Initializes a new instance of the MessageInfo class.
        /// </summary>
        public MessageInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageInfo class.
        /// </summary>
        public MessageInfo(string id = default(string), string content = default(string))
        {
            Id = id;
            Content = content;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }

    }
}
