// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Streetcred.Cloud.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Wallet information
    /// </summary>
    public partial class WalletInfo
    {
        /// <summary>
        /// Initializes a new instance of the WalletInfo class.
        /// </summary>
        public WalletInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WalletInfo class.
        /// </summary>
        /// <param name="type">Gets or sets the type.</param>
        /// <param name="id">Gets or sets the identifier.</param>
        /// <param name="name">Gets or sets the name.</param>
        public WalletInfo(string type = default(string), string id = default(string), string name = default(string))
        {
            Type = type;
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
