/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const IFormFile: msRest.CompositeMapper = {
  serializedName: "IFormFile",
  type: {
    name: "Composite",
    className: "IFormFile",
    modelProperties: {
      contentType: {
        readOnly: true,
        serializedName: "contentType",
        type: {
          name: "String"
        }
      },
      contentDisposition: {
        readOnly: true,
        serializedName: "contentDisposition",
        type: {
          name: "String"
        }
      },
      headers: {
        readOnly: true,
        serializedName: "headers",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "String"
                }
              }
            }
          }
        }
      },
      length: {
        readOnly: true,
        serializedName: "length",
        type: {
          name: "Number"
        }
      },
      name: {
        readOnly: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      fileName: {
        readOnly: true,
        serializedName: "fileName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const NetworkContract: msRest.CompositeMapper = {
  serializedName: "NetworkContract",
  type: {
    name: "Composite",
    className: "NetworkContract",
    modelProperties: {
      networkId: {
        serializedName: "network_id",
        type: {
          name: "String"
        }
      },
      networkName: {
        serializedName: "network_name",
        type: {
          name: "String"
        }
      },
      genesisTransactions: {
        serializedName: "genesis_transactions",
        type: {
          name: "String"
        }
      },
      poolProtocolVersion: {
        serializedName: "pool_protocol_version",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const AgentEndpoint: msRest.CompositeMapper = {
  serializedName: "AgentEndpoint",
  type: {
    name: "Composite",
    className: "AgentEndpoint",
    modelProperties: {
      did: {
        serializedName: "did",
        type: {
          name: "String"
        }
      },
      verkey: {
        serializedName: "verkey",
        type: {
          name: "String"
        }
      },
      uri: {
        serializedName: "uri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConnectionContract: msRest.CompositeMapper = {
  serializedName: "ConnectionContract",
  type: {
    name: "Composite",
    className: "ConnectionContract",
    modelProperties: {
      connectionId: {
        serializedName: "connectionId",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      imageUrl: {
        serializedName: "imageUrl",
        type: {
          name: "String"
        }
      },
      myDid: {
        serializedName: "myDid",
        type: {
          name: "String"
        }
      },
      theirDid: {
        serializedName: "theirDid",
        type: {
          name: "String"
        }
      },
      myKey: {
        serializedName: "myKey",
        type: {
          name: "String"
        }
      },
      theirKey: {
        serializedName: "theirKey",
        type: {
          name: "String"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      invitation: {
        serializedName: "invitation",
        type: {
          name: "String"
        }
      },
      invitationUrl: {
        serializedName: "invitationUrl",
        type: {
          name: "String"
        }
      },
      endpoint: {
        serializedName: "endpoint",
        type: {
          name: "Composite",
          className: "AgentEndpoint"
        }
      },
      createdAtUtc: {
        serializedName: "createdAtUtc",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const ConnectionInvitationParameters: msRest.CompositeMapper = {
  serializedName: "ConnectionInvitationParameters",
  type: {
    name: "Composite",
    className: "ConnectionInvitationParameters",
    modelProperties: {
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      multiParty: {
        serializedName: "multi_party",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const IdContract: msRest.CompositeMapper = {
  serializedName: "IdContract",
  type: {
    name: "Composite",
    className: "IdContract",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CredentialContract: msRest.CompositeMapper = {
  serializedName: "CredentialContract",
  type: {
    name: "Composite",
    className: "CredentialContract",
    modelProperties: {
      credentialId: {
        serializedName: "credentialId",
        type: {
          name: "String"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      connectionId: {
        serializedName: "connectionId",
        type: {
          name: "String"
        }
      },
      definitionId: {
        serializedName: "definitionId",
        type: {
          name: "String"
        }
      },
      schemaId: {
        serializedName: "schemaId",
        type: {
          name: "String"
        }
      },
      values: {
        serializedName: "values",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const CredentialOfferParameters: msRest.CompositeMapper = {
  serializedName: "CredentialOfferParameters",
  type: {
    name: "Composite",
    className: "CredentialOfferParameters",
    modelProperties: {
      definitionId: {
        serializedName: "definitionId",
        type: {
          name: "String"
        }
      },
      connectionId: {
        serializedName: "connectionId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CredentialDefinitionContract: msRest.CompositeMapper = {
  serializedName: "CredentialDefinitionContract",
  type: {
    name: "Composite",
    className: "CredentialDefinitionContract",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      supportsRevocation: {
        serializedName: "supportsRevocation",
        type: {
          name: "Boolean"
        }
      },
      maxCredentialCount: {
        serializedName: "maxCredentialCount",
        type: {
          name: "Number"
        }
      },
      schemaId: {
        serializedName: "schemaId",
        type: {
          name: "String"
        }
      },
      definitionId: {
        serializedName: "definitionId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CredentialDefinitionParameters: msRest.CompositeMapper = {
  serializedName: "CredentialDefinitionParameters",
  type: {
    name: "Composite",
    className: "CredentialDefinitionParameters",
    modelProperties: {
      schemaId: {
        serializedName: "schema_id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      attrNames: {
        serializedName: "attr_names",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      supportRevocation: {
        serializedName: "support_revocation",
        type: {
          name: "Boolean"
        }
      },
      maxCount: {
        serializedName: "max_count",
        type: {
          name: "Number"
        }
      },
      tag: {
        serializedName: "tag",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SchemaParameters: msRest.CompositeMapper = {
  serializedName: "SchemaParameters",
  type: {
    name: "Composite",
    className: "SchemaParameters",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      attrNames: {
        serializedName: "attr_names",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const SchemaRecord: msRest.CompositeMapper = {
  serializedName: "SchemaRecord",
  type: {
    name: "Composite",
    className: "SchemaRecord",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      attributeNames: {
        serializedName: "attributeNames",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TenantContract: msRest.CompositeMapper = {
  serializedName: "TenantContract",
  type: {
    name: "Composite",
    className: "TenantContract",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      imageUrl: {
        serializedName: "imageUrl",
        type: {
          name: "String"
        }
      },
      network: {
        serializedName: "network",
        type: {
          name: "Composite",
          className: "NetworkContract"
        }
      },
      tenantId: {
        serializedName: "tenantId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TenantParameters: msRest.CompositeMapper = {
  serializedName: "TenantParameters",
  type: {
    name: "Composite",
    className: "TenantParameters",
    modelProperties: {
      issuerSeed: {
        serializedName: "issuer_seed",
        type: {
          name: "String"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      imageUrl: {
        serializedName: "image_url",
        type: {
          name: "String"
        }
      },
      networkId: {
        serializedName: "network_id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const VerificationContract: msRest.CompositeMapper = {
  serializedName: "VerificationContract",
  type: {
    name: "Composite",
    className: "VerificationContract",
    modelProperties: {
      connectionId: {
        serializedName: "connectionId",
        type: {
          name: "String"
        }
      },
      verificationId: {
        serializedName: "verificationId",
        type: {
          name: "String"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      createdAtUtc: {
        serializedName: "createdAtUtc",
        type: {
          name: "DateTime"
        }
      },
      updatedAtUtc: {
        serializedName: "updatedAtUtc",
        type: {
          name: "DateTime"
        }
      },
      isValid: {
        serializedName: "isValid",
        type: {
          name: "Boolean"
        }
      },
      verifiedAtUtc: {
        serializedName: "verifiedAtUtc",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const VerificationParameters: msRest.CompositeMapper = {
  serializedName: "VerificationParameters",
  type: {
    name: "Composite",
    className: "VerificationParameters",
    modelProperties: {
      proofRequestId: {
        serializedName: "proofRequestId",
        type: {
          name: "String"
        }
      },
      connectionId: {
        serializedName: "connectionId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const AttributeFilter: msRest.CompositeMapper = {
  serializedName: "AttributeFilter",
  type: {
    name: "Composite",
    className: "AttributeFilter",
    modelProperties: {
      schemaId: {
        serializedName: "schema_id",
        type: {
          name: "String"
        }
      },
      schemaIssuerDid: {
        serializedName: "schema_issuer_did",
        type: {
          name: "String"
        }
      },
      schemaName: {
        serializedName: "schema_name",
        type: {
          name: "String"
        }
      },
      schemaVersion: {
        serializedName: "schema_version",
        type: {
          name: "String"
        }
      },
      issuerDid: {
        serializedName: "issuer_did",
        type: {
          name: "String"
        }
      },
      credDefId: {
        serializedName: "cred_def_id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RevocationInterval: msRest.CompositeMapper = {
  serializedName: "RevocationInterval",
  type: {
    name: "Composite",
    className: "RevocationInterval",
    modelProperties: {
      from: {
        serializedName: "from",
        type: {
          name: "Number"
        }
      },
      to: {
        serializedName: "to",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ProofAttributeInfo: msRest.CompositeMapper = {
  serializedName: "ProofAttributeInfo",
  type: {
    name: "Composite",
    className: "ProofAttributeInfo",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      restrictions: {
        serializedName: "restrictions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AttributeFilter"
            }
          }
        }
      },
      nonRevoked: {
        serializedName: "non_revoked",
        type: {
          name: "Composite",
          className: "RevocationInterval"
        }
      }
    }
  }
};

export const ProofPredicateInfo: msRest.CompositeMapper = {
  serializedName: "ProofPredicateInfo",
  type: {
    name: "Composite",
    className: "ProofPredicateInfo",
    modelProperties: {
      pType: {
        serializedName: "p_type",
        type: {
          name: "String"
        }
      },
      pValue: {
        serializedName: "p_value",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      restrictions: {
        serializedName: "restrictions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AttributeFilter"
            }
          }
        }
      },
      nonRevoked: {
        serializedName: "non_revoked",
        type: {
          name: "Composite",
          className: "RevocationInterval"
        }
      }
    }
  }
};

export const ProofRequest: msRest.CompositeMapper = {
  serializedName: "ProofRequest",
  type: {
    name: "Composite",
    className: "ProofRequest",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      nonce: {
        serializedName: "nonce",
        type: {
          name: "String"
        }
      },
      requestedAttributes: {
        serializedName: "requested_attributes",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "ProofAttributeInfo"
            }
          }
        }
      },
      requestedPredicates: {
        serializedName: "requested_predicates",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "ProofPredicateInfo"
            }
          }
        }
      },
      nonRevoked: {
        serializedName: "non_revoked",
        type: {
          name: "Composite",
          className: "RevocationInterval"
        }
      }
    }
  }
};

export const VerificationDefinitionContract: msRest.CompositeMapper = {
  serializedName: "VerificationDefinitionContract",
  type: {
    name: "Composite",
    className: "VerificationDefinitionContract",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "ProofRequest"
        }
      }
    }
  }
};
