/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const connectionId0: msRest.OperationURLParameter = {
  parameterPath: "connectionId",
  mapper: {
    required: true,
    serializedName: "connectionId",
    type: {
      name: "String"
    }
  }
};
export const connectionId1: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "connectionId"
  ],
  mapper: {
    serializedName: "connectionId",
    type: {
      name: "String"
    }
  }
};
export const contentType: msRest.OperationParameter = {
  parameterPath: [
    "options",
    "contentType"
  ],
  mapper: {
    serializedName: "contentType",
    type: {
      name: "String"
    }
  }
};
export const credentialId: msRest.OperationURLParameter = {
  parameterPath: "credentialId",
  mapper: {
    required: true,
    serializedName: "credentialId",
    type: {
      name: "String"
    }
  }
};
export const definitionId: msRest.OperationURLParameter = {
  parameterPath: "definitionId",
  mapper: {
    required: true,
    serializedName: "definitionId",
    type: {
      name: "String"
    }
  }
};
export const filename: msRest.OperationParameter = {
  parameterPath: [
    "options",
    "filename"
  ],
  mapper: {
    serializedName: "filename",
    type: {
      name: "String"
    }
  }
};
export const state: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "state"
  ],
  mapper: {
    serializedName: "state",
    type: {
      name: "String"
    }
  }
};
export const tenantId: msRest.OperationURLParameter = {
  parameterPath: "tenantId",
  mapper: {
    required: true,
    serializedName: "tenantId",
    type: {
      name: "String"
    }
  }
};
export const uploadedFiles: msRest.OperationParameter = {
  parameterPath: [
    "options",
    "uploadedFiles"
  ],
  mapper: {
    serializedName: "uploadedFiles",
    type: {
      name: "Stream"
    }
  }
};
export const verificationId: msRest.OperationURLParameter = {
  parameterPath: "verificationId",
  mapper: {
    required: true,
    serializedName: "verificationId",
    type: {
      name: "String"
    }
  }
};
export const xStreetcredTenantId: msRest.OperationParameter = {
  parameterPath: "xStreetcredTenantId",
  mapper: {
    required: true,
    serializedName: "X-Streetcred-Tenant-Id",
    type: {
      name: "String"
    }
  }
};
