source "https://rubygems.org"

# Specify your gem's dependencies in test-gem.gemspec
gemspec

gem "uri"
gem "cgi"
gem "date"
gem "json"
gem "timeliness"
gem "faraday"
gem "faraday-cookie_jar"
gem "ms_rest"
gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"
