# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ConnectionInvitationParameters(Model):
    """Connection invitation parameters.

    :param connection_id: Unique connection identifier. If not specified, a
     random one will be generated.
    :type connection_id: str
    :param multi_party: If set to 'true', the invitation can be used by
     multiple parties and will always have the status set to 'Invited'.
     When a party accepts this invitation, a new connection record with a
     unique identifier will be created.
     Default value is 'false'.
    :type multi_party: bool
    :param name: Name that can be used as an alias for the connection.
     Default value is 'null'.
    :type name: str
    """

    _attribute_map = {
        'connection_id': {'key': 'connectionId', 'type': 'str'},
        'multi_party': {'key': 'multiParty', 'type': 'bool'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ConnectionInvitationParameters, self).__init__(**kwargs)
        self.connection_id = kwargs.get('connection_id', None)
        self.multi_party = kwargs.get('multi_party', None)
        self.name = kwargs.get('name', None)
