# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CredentialDefinitionFromSchemaParameters(Model):
    """Represents a request object to create new credential definition for an
    agency.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. Schema name
    :type name: str
    :param version: Required. Schema version
    :type version: str
    :param attributes: Required. Schema attribute names
    :type attributes: list[str]
    :param support_revocation: Support credential revocation
    :type support_revocation: bool
    :param tag: Unique tag to differentiate definitions of the same schema
    :type tag: str
    """

    _validation = {
        'name': {'required': True},
        'version': {'required': True},
        'attributes': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': '[str]'},
        'support_revocation': {'key': 'supportRevocation', 'type': 'bool'},
        'tag': {'key': 'tag', 'type': 'str'},
    }

    def __init__(self, *, name: str, version: str, attributes, support_revocation: bool=None, tag: str=None, **kwargs) -> None:
        super(CredentialDefinitionFromSchemaParameters, self).__init__(**kwargs)
        self.name = name
        self.version = version
        self.attributes = attributes
        self.support_revocation = support_revocation
        self.tag = tag
