# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class NetworkTxnAgreementContract(Model):
    """Transaction author agreement.

    :param text: Acceptance agreement text
    :type text: str
    :param version: Agreement version
    :type version: str
    :param acceptance_methods: List of agreement acceptance methods
    :type acceptance_methods: dict[str, str]
    """

    _attribute_map = {
        'text': {'key': 'text', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'acceptance_methods': {'key': 'acceptanceMethods', 'type': '{str}'},
    }

    def __init__(self, **kwargs):
        super(NetworkTxnAgreementContract, self).__init__(**kwargs)
        self.text = kwargs.get('text', None)
        self.version = kwargs.get('version', None)
        self.acceptance_methods = kwargs.get('acceptance_methods', None)
