# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProofRequest(Model):
    """ProofRequest.

    :param name:
    :type name: str
    :param version:
    :type version: str
    :param nonce:
    :type nonce: str
    :param requested_attributes:
    :type requested_attributes: dict[str,
     ~credentials.models.ProofAttributeInfo]
    :param requested_predicates:
    :type requested_predicates: dict[str,
     ~credentials.models.ProofPredicateInfo]
    :param non_revoked:
    :type non_revoked: ~credentials.models.RevocationInterval
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'nonce': {'key': 'nonce', 'type': 'str'},
        'requested_attributes': {'key': 'requestedAttributes', 'type': '{ProofAttributeInfo}'},
        'requested_predicates': {'key': 'requestedPredicates', 'type': '{ProofPredicateInfo}'},
        'non_revoked': {'key': 'nonRevoked', 'type': 'RevocationInterval'},
    }

    def __init__(self, *, name: str=None, version: str=None, nonce: str=None, requested_attributes=None, requested_predicates=None, non_revoked=None, **kwargs) -> None:
        super(ProofRequest, self).__init__(**kwargs)
        self.name = name
        self.version = version
        self.nonce = nonce
        self.requested_attributes = requested_attributes
        self.requested_predicates = requested_predicates
        self.non_revoked = non_revoked
