# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RevocationInterval(Model):
    """RevocationInterval.

    :param from_property:
    :type from_property: int
    :param to:
    :type to: int
    """

    _attribute_map = {
        'from_property': {'key': 'from', 'type': 'int'},
        'to': {'key': 'to', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(RevocationInterval, self).__init__(**kwargs)
        self.from_property = kwargs.get('from_property', None)
        self.to = kwargs.get('to', None)
