# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VerificationDefinitionContract(Model):
    """VerificationDefinitionContract.

    :param id: The verification identifier
    :type id: str
    :param proof_request:
    :type proof_request: ~credentials.models.ProofRequest
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'proof_request': {'key': 'proofRequest', 'type': 'ProofRequest'},
    }

    def __init__(self, *, id: str=None, proof_request=None, **kwargs) -> None:
        super(VerificationDefinitionContract, self).__init__(**kwargs)
        self.id = id
        self.proof_request = proof_request
