# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VerificationPolicyContract(Model):
    """VerificationPolicyContract.

    All required parameters must be populated in order to send to Azure.

    :param policy_id:
    :type policy_id: str
    :param name: Required.
    :type name: str
    :param version: Required.
    :type version: str
    :param attributes:
    :type attributes:
     list[~credentials.models.VerificationPolicyAttributeContract]
    :param predicates:
    :type predicates:
     list[~credentials.models.VerificationPolicyPredicateContract]
    :param revocation_requirement:
    :type revocation_requirement:
     ~credentials.models.VerificationPolicyRevocationRequirement
    """

    _validation = {
        'name': {'required': True},
        'version': {'required': True},
    }

    _attribute_map = {
        'policy_id': {'key': 'policyId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': '[VerificationPolicyAttributeContract]'},
        'predicates': {'key': 'predicates', 'type': '[VerificationPolicyPredicateContract]'},
        'revocation_requirement': {'key': 'revocationRequirement', 'type': 'VerificationPolicyRevocationRequirement'},
    }

    def __init__(self, *, name: str, version: str, policy_id: str=None, attributes=None, predicates=None, revocation_requirement=None, **kwargs) -> None:
        super(VerificationPolicyContract, self).__init__(**kwargs)
        self.policy_id = policy_id
        self.name = name
        self.version = version
        self.attributes = attributes
        self.predicates = predicates
        self.revocation_requirement = revocation_requirement
