# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WebhookParameters(Model):
    """WebhookParameters.

    :param url:
    :type url: str
    :param type: Possible values include: 'Notification', 'DelegatedEndorser',
     'Zapier'
    :type type: str or ~credentials.models.enum
    :param parameters:
    :type parameters: str
    """

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(WebhookParameters, self).__init__(**kwargs)
        self.url = kwargs.get('url', None)
        self.type = kwargs.get('type', None)
        self.parameters = kwargs.get('parameters', None)
