# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .cloud_wallet_analytics_contract_py3 import CloudWalletAnalyticsContract
    from .usage_contract_py3 import UsageContract
    from .asset_contract_py3 import AssetContract
    from .network_contract_py3 import NetworkContract
    from .tenant_extended_information_contract_py3 import TenantExtendedInformationContract
    from .tenant_contract_py3 import TenantContract
    from .tenant_parameters_py3 import TenantParameters
    from .tenant_update_parameters_py3 import TenantUpdateParameters
    from .tenant_keys_contract_py3 import TenantKeysContract
except (SyntaxError, ImportError):
    from .cloud_wallet_analytics_contract import CloudWalletAnalyticsContract
    from .usage_contract import UsageContract
    from .asset_contract import AssetContract
    from .network_contract import NetworkContract
    from .tenant_extended_information_contract import TenantExtendedInformationContract
    from .tenant_contract import TenantContract
    from .tenant_parameters import TenantParameters
    from .tenant_update_parameters import TenantUpdateParameters
    from .tenant_keys_contract import TenantKeysContract

__all__ = [
    'CloudWalletAnalyticsContract',
    'UsageContract',
    'AssetContract',
    'NetworkContract',
    'TenantExtendedInformationContract',
    'TenantContract',
    'TenantParameters',
    'TenantUpdateParameters',
    'TenantKeysContract',
]
