# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TenantKeysContract(Model):
    """Tenant keys.

    :param access_token: JWT Access Token that authorizes API calls for the
     organization
    :type access_token: str
    :param subscription_key: Identifies and authenticates your subscription
    :type subscription_key: str
    """

    _attribute_map = {
        'access_token': {'key': 'accessToken', 'type': 'str'},
        'subscription_key': {'key': 'subscriptionKey', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(TenantKeysContract, self).__init__(**kwargs)
        self.access_token = kwargs.get('access_token', None)
        self.subscription_key = kwargs.get('subscription_key', None)
