# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TenantUpdateParameters(Model):
    """Tenant update parameters.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. The tenant name
    :type name: str
    :param image_url: URL of tenant image
    :type image_url: str
    """

    _validation = {
        'name': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'image_url': {'key': 'imageUrl', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(TenantUpdateParameters, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.image_url = kwargs.get('image_url', None)
